### PR TITLE
Plotting seaborn.FacetGrid compatibility

### PR DESCRIPTION
**Pull request by remrama**
This addresses a feature request in #306 to offer more flexibility in pingouin's plotting module. The changes were targeted at making some of the functions useable with the `g.map_dataframe()` method attached to seaborn grids, but they offer more flexibility when used alone as well.

The main things:
* Removed all fig and dpi keyword arguments (users should be advised to generate their own figures first, eg with `plt.subplot` and then pass the `ax` to pingouin)
* Removed the `plot_blandaltmann` keyword argument `scatter_kws` and now any `kwarg` gets passed through. This was done because `gmap_dataframe` requires the passing of a `color` keyword (and `label`), and it can be useful at times.
* Note that now, without passing `fig` through, the default axis that pops up is not always square. So for the few plotting functions that probably _should_ be square (qqplot, circmean), I added an `ax.set_aspect("equal")` in the docstring examples.

If you want to see some arbitrary examples of the use-case I'm talking about:

```python
import pingouin as pg
import seaborn as sns
import matplotlib.pyplot as plt

iris = sns.load_dataset("iris")

g = sns.FacetGrid(iris, col="species", aspect=1)
g.map(pg.qqplot, "petal_width")
plt.show()

g = sns.FacetGrid(iris, col="species", hue="species", sharey=False)
g.map(pg.plot_blandaltman, "petal_width", "sepal_width")
plt.show()
```

### CODE REVIEW

**Comment by raphaelvallat** [comment]
Hi @remrama,

Thanks for the PR, great idea! A few comments:

- [ ] Can you please update the unit tests?
- [ ] Update the changelog
- [ ] Does this require to bump seaborn's version in the requirements/setup?
- [ ] I do feel that`ax.set_aspect("equal")` should be the default for qqplot and circmean. Is there a way that we could ensure that, e.g. by including a `square=True` parameter like in seaborn.heatmap?

**Comment by raphaelvallat** [comment]
@remrama I've rebased the PR to master, make sure you `git pull` before making new changes!

**Comment by remrama** [comment]
@raphaelvallat I think this is good to go?

It passes unittests, changelog is updated, and `square` keyword arguments were added to `qqplot()` and `plot_circmean()`. Nothing to worry about for seaborn version requirements. `map()` was present in version 0.10, and you already require 0.11.

**Review by raphaelvallat — APPROVED** [review]

**Comment by raphaelvallat** [comment]
@remrama just made some very minor edits to documentation. Merging when the CIs are complete

**Pull request merged**
