### PR TITLE
Add check for noncentrality parameters.

### LINKED ISSUE #343: Crash when calculating power with too large effect size
This crash occurs for me with the following code, although it may not work identically on all platforms:
```python
import numpy as np
from pingouin.effsize import compute_effsize
from pingouin.power import power_ttest

x = np.ones(10) * 0.3
y = np.ones(10) * 0.6
d = compute_effsize(x, y, paired=True)
print(d)
print(power_ttest(d, x.size))
```
Running this code results in the output
```
-3242591731706756.5
terminate called after throwing an instance of 'boost::wrapexcept<boost::math::rounding_error>'
  what():  Error in function boost::math::itrunc<double>(double): Value 2.3657402561699292e+31 can not be represented in the target integer type.
Aborted (core dumped)
```

The root cause of this is related to https://github.com/scipy/scipy/issues/17916. However, it occurs in `power_ttest()` due to calling `scipy.stats.nct.cdf()` with the huge value of `nc` based on `d`:
https://github.com/raphaelvallat/pingouin/blob/c66b6853cfcbe1d6d9702c87c09050594b4cacb4/pingouin/power.py#L146-L168

Perhaps a check should be done in `compute_effsize()` to check whether the variance to too small? Or check whether the effect size magnitude is too high in `power_ttest()`?

### PR DESCRIPTION
**Pull request by agkphysics**
Fixes #343, caused by scipy/scipy#17916.

### CODE REVIEW

**Comment by agkphysics** [comment]
I notice that coverage fails because of the `greater` and `less` paths. Do you want me to add these extra test cases for `ttest` and `ttest2n`?

**Comment by raphaelvallat** [comment]
Hi @agkphysics,

This is great, thank you! Yes can you please add the extra test? 

Btw I see that https://github.com/scipy/scipy/issues/17916 has now been fixed and should be included in scipy 1.11.0.

**Comment by agkphysics** [comment]
@raphaelvallat I have added the additional tests now.

**Review by raphaelvallat — APPROVED** [review]
Approved! Thanks so much

**Pull request merged**
