### PR TITLE
optional arguments for logistic_regression() in mediation_analysis()

### PR DESCRIPTION
**Pull request by julibeg**
As discussed in #244.

I added a dict `logreg_kwargs` with the arguments for logistic regression instead of `**kwargs` as this might be cleaner at some later time when you might also want to pass arguments to other functions called by `mediation_analysis()` (e.g. `linear_regression()`). If you prefer the `**kwargs` solution, let me know and I'll change it.

Also, I'm not really familiar with Sphinx, please check if the docstring correct.

### CODE REVIEW

**Comment by raphaelvallat** [comment]
Hi @julibeg,

That looks great, thanks! Have you made sure that changing the `logreg_kwargs` change the output of the mediation analysis? Could you perhaps add just one test in the [test_regression.py](https://github.com/raphaelvallat/pingouin/blob/master/pingouin/tests/test_regression.py) file?

Thanks,
Raphael

**Comment by julibeg** [comment]
I made sure by printing the `kwargs` right before `lom.fit(X, y)` in `logistic_regression()` (i.e. [here](https://github.com/raphaelvallat/pingouin/blob/899774de1386e7f038bd8945f6333e4349964f7b/pingouin/regression.py#L872)), but I can also add a test.

**Comment by julibeg** [comment]
OK, I added some more code to test for differences in the actual results.
Something else I noticed: When testing the indirect effect with `assert_almost_equal(ma['coef'][4], 0.0033, decimal=2)`, `2` might not be strict enough for the test to be meaningful, maybe replace it with '3'.

**Comment by raphaelvallat** [comment]
Hi @julibeg,

Thanks! I agree we can use `decimal=3`. However, can you explain what these added lines do:

```python
 with pytest.raises(AssertionError):
    assert_almost_equal(ma['coef'][0], -0.0208, decimal=2)
with pytest.raises(AssertionError):
    assert_almost_equal(ma['coef'][4], 0.0033, decimal=3)
```

Right now, this will test that ma['coef'][0] is **not** equal to -0.0208, and as a result throw an assertion error. Is this the correct behavior?

Thank you
Raphael

**Comment by julibeg** [comment]
```python
# Solve with 0 iterations and make sure that the results are different
ma = mediation_analysis(data=df, x='X', m='Mbin', y='Y', n_boot=2000,
                        logreg_kwargs=dict(max_iter=0))
```
This runs the mediation analysis while not allowing the solver to iterate so that the results are different (however, weirdly not all the coefs are different, just `coef[0]` and `coef[4]`). 
```
with pytest.raises(AssertionError):
    assert_almost_equal(ma['coef'][0], -0.0208, decimal=2)
with pytest.raises(AssertionError):
    assert_almost_equal(ma['coef'][4], 0.0033, decimal=3)

```
This checks that the coefs are indeed different and that the assertion fails.

**Comment by raphaelvallat** [comment]
Got it, thanks! So are we ready to merge?

**Comment by julibeg** [comment]
I think so

**Review by raphaelvallat — APPROVED** [review]

**Pull request merged**
