### PR TITLE
Rename pairwise_ttests to pairwise_tests

### PR DESCRIPTION
**Pull request by michalkahle**
PR for issue #209 .

### CODE REVIEW

**Comment by michalkahle** [comment]
The name of the function is still wrong in the image `flowchart_one_way_ANOVA.svg` because the letters are encoded as paths. I'm not sure how to fix this.

**Comment by raphaelvallat** [comment]
Thank you @michalkahle, this is great. I'll add a commit with the following changes:

- [ ] re-export the svg files
- [ ] update the changelog.rst file

**Comment by raphaelvallat** [comment]
Done! Feel free to edit the changelog -- I think we're good to merge?

**Comment by michalkahle** [comment]
Yes, it's perfect. Thank you!

**Review by raphaelvallat — APPROVED** [review]
Good to merge!

**Pull request merged**
