### PR TITLE
Add aesthetic flexibility to plot_rm_corr

### PR DESCRIPTION
**Pull request by remrama**
Hi @raphaelvallat - I love the `plot_rm_corr` function and needed some flexibility to change its scatter and line features (e.g., marker size and line width). I made a simple change to allow this, adding two sets of kwargs that get passed through to seaborn. Nothing about the defaults have changed, it just offers flexibility if desired.

Sorry I didn't open an Issue first, it was just such a straight-forward change I thought I'd go for it. No pressure if you want to reject this idea.

### CODE REVIEW

**Comment by raphaelvallat** [comment]
Hi @remrama,

Thanks for opening the PR! Looks great. Two things:

- [ ] Can you please remove `pytest-travis-fold` from the [requirements-test.txt](https://github.com/raphaelvallat/pingouin/blob/master/requirements-test.txt) file? This should solve the CI failure.
- [ ] Can you please add this to the [changelog](https://github.com/raphaelvallat/pingouin/blob/master/docs/changelog.rst#v0-6-0-dev)? Under a new section "Improvements"?

**Comment by raphaelvallat** [comment]
Let me know when the PR is ready for review/merge 👍

**Comment by remrama** [comment]
Yep it's good for review! I made the suggested changes.

**Review by raphaelvallat — APPROVED** [review]

**Comment by raphaelvallat** [comment]
Merged, thanks!

**Pull request merged**
