### PR TITLE
Handle single-sample comparsion in pairwise_test

### PR DESCRIPTION
**Pull request by George3d6**
Due to a scipy interface change the pairwise_test can fail when obtaining the t-value from a single sample comparison, this, I believe, fixes that issue.

### CODE REVIEW

**Comment by raphaelvallat** [comment]
Hi @George3d6,

Thank you for this!

1. Can you be more specific about which versions of SciPy have this potential bug? Did it appear in SciPy 1.9?
2. Does this issue only occur for one-sample T-tests?
3. There seems to be an unrelated unit test failure, I'll fix that now

**Comment by George3d6** [comment]
I'm actually unsure when the scipy interface might have changed, or if this was always the case, I'll look into it.
But as can bee seen, the current scipy interface is returning a tuple that the code treats as expecting to be a float or int, so the impl is most certainly wrong

**Comment by George3d6** [comment]
@raphaelvallat as far as I can see this isn't a recent change in the scipy interface as I suspected, so I guess the bug was always there.

**Review by raphaelvallat — APPROVED** [review]

**Comment by raphaelvallat** [comment]
Got it, well I think we're good to merge. Thanks again for the PR!

**Pull request merged**
